[package]
name = "orbweaver"
version = "0.1.0"
authors = ["karim"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input-linux-sys = "0.3.1"
libc = "0.2.71"
keycodes = "0.1.0"
